name: textreturn
services:
    state:
        method: GET
        service: VEHICLE-STATE
    command:
        method: GET, POST
        service: COMMAND-API
    schedule:
        method: POST
        service: SCHEDULER-API
        
parent: 
    present:
        foo: dey, tok
        bar: ar, jerbs
    later:
        foo: dey, dok
        mar: r, jeurbs
spring:
  zipkin:
      baseUrl: http://distributed-tracer.apps.cl-east-dev02.cf.ford.com
  sleuth:
    sampler:
      percentage: 1.0
test: prodss