# Azure OAuth2 properties
azure:
  tenantId: '{cipher}27c43ed58dedea072f18cae3230ea9cce7101a3e801c235db7a4d26ab7c27e535198d7ebc420e5758aa7d40f1412e85fcf13d2529a236f21cb0254b56f72bead'
  oauth2:
    v1:
      resource:
        wellKnownEndpoint: https://login.microsoftonline.com/${azure.tenantId}/.well-known/openid-configuration
        keySource: https://login.microsoftonline.com/${azure.tenantId}/discovery/keys